version: '3'
services:
  SCN-0:
    hostname: SCN-0
    image: klaytn/klaytn:latest
    ports:
      - '32320:32323'
      - '8550:8551'
      - '61000:61001'
      - '50500:50506'
    entrypoint: /bin/sh
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      app_net:
        ipv4_address: 172.16.239.10
    volumes:
      - ./homi-output:/klaytn
    restart: "no"
  SCN-1:
    hostname: SCN-1
    image: klaytn/klaytn:latest
    ports:
      - '32321:32323'
      - '8551:8551'
      - '61001:61001'
      - '50501:50506'
    entrypoint: /bin/sh
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      app_net:
        ipv4_address: 172.16.239.11
    volumes:
      - ./homi-output:/klaytn
    restart: "no"
  SCN-2:
    hostname: SCN-2
    image: klaytn/klaytn:latest
    ports:
      - '32322:32323'
      - '8552:8551'
      - '61002:61001'
      - '50502:50506'
    entrypoint: /bin/sh
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      app_net:
        ipv4_address: 172.16.239.12
    volumes:
      - ./homi-output:/klaytn
    restart: "no"
  SCN-3:
    hostname: SCN-3
    image: klaytn/klaytn:latest
    ports:
      - '32323:32323'
      - '8553:8551'
      - '61003:61001'
      - '50503:50506'
    entrypoint: /bin/sh
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      app_net:
        ipv4_address: 172.16.239.13
    volumes:
      - ./homi-output:/klaytn
    restart: "no"
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24